# Generated by Django 5.0 on 2023-12-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2003-05-02'),
            preserve_default=False,
        ),
    ]
